// Copyright 2021-2022 by Nedim Sabic Sabic
// https://www.fibratus.io
// All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: fleet/v1/fleet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsVersion     string                 `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	EngineVersion string                 `protobuf:"bytes,3,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	AgentGroup    string                 `protobuf:"bytes,4,opt,name=agent_group,json=agentGroup,proto3" json:"agent_group,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *RegisterRequest) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *RegisterRequest) GetAgentGroup() string {
	if x != nil {
		return x.AgentGroup
	}
	return ""
}

func (x *RegisterRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RulesVersion  string                 `protobuf:"bytes,3,opt,name=rules_version,json=rulesVersion,proto3" json:"rules_version,omitempty"`
	CpuPct        float64                `protobuf:"fixed64,4,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`
	MemMb         uint64                 `protobuf:"varint,5,opt,name=mem_mb,json=memMb,proto3" json:"mem_mb,omitempty"`
	EventsPerSec  float64                `protobuf:"fixed64,6,opt,name=events_per_sec,json=eventsPerSec,proto3" json:"events_per_sec,omitempty"`
	ActiveRules   int32                  `protobuf:"varint,7,opt,name=active_rules,json=activeRules,proto3" json:"active_rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartbeatRequest) GetRulesVersion() string {
	if x != nil {
		return x.RulesVersion
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuPct() float64 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *HeartbeatRequest) GetMemMb() uint64 {
	if x != nil {
		return x.MemMb
	}
	return 0
}

func (x *HeartbeatRequest) GetEventsPerSec() float64 {
	if x != nil {
		return x.EventsPerSec
	}
	return 0
}

func (x *HeartbeatRequest) GetActiveRules() int32 {
	if x != nil {
		return x.ActiveRules
	}
	return 0
}

type HeartbeatResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TamperProtection   bool                   `protobuf:"varint,2,opt,name=tamper_protection,json=tamperProtection,proto3" json:"tamper_protection,omitempty"`
	Isolated           bool                   `protobuf:"varint,3,opt,name=isolated,proto3" json:"isolated,omitempty"`
	IsolationWhitelist []string               `protobuf:"bytes,4,rep,name=isolation_whitelist,json=isolationWhitelist,proto3" json:"isolation_whitelist,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatResponse) GetTamperProtection() bool {
	if x != nil {
		return x.TamperProtection
	}
	return false
}

func (x *HeartbeatResponse) GetIsolated() bool {
	if x != nil {
		return x.Isolated
	}
	return false
}

func (x *HeartbeatResponse) GetIsolationWhitelist() []string {
	if x != nil {
		return x.IsolationWhitelist
	}
	return nil
}

type TelemetryEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Seq            int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventName      string                 `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventCategory  string                 `protobuf:"bytes,4,opt,name=event_category,json=eventCategory,proto3" json:"event_category,omitempty"`
	Pid            uint32                 `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	Tid            uint32                 `protobuf:"varint,6,opt,name=tid,proto3" json:"tid,omitempty"`
	ProcessName    string                 `protobuf:"bytes,7,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	ProcessExe     string                 `protobuf:"bytes,8,opt,name=process_exe,json=processExe,proto3" json:"process_exe,omitempty"`
	ProcessCmdline string                 `protobuf:"bytes,9,opt,name=process_cmdline,json=processCmdline,proto3" json:"process_cmdline,omitempty"`
	ParentPid      uint32                 `protobuf:"varint,10,opt,name=parent_pid,json=parentPid,proto3" json:"parent_pid,omitempty"`
	ParentName     string                 `protobuf:"bytes,11,opt,name=parent_name,json=parentName,proto3" json:"parent_name,omitempty"`
	// Structured params, metadata, and raw event stored as JSON bytes
	// for maximum flexibility and ClickHouse compatibility.
	Params        []byte `protobuf:"bytes,12,opt,name=params,proto3" json:"params,omitempty"`
	Metadata      []byte `protobuf:"bytes,13,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RawEvent      []byte `protobuf:"bytes,14,opt,name=raw_event,json=rawEvent,proto3" json:"raw_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *TelemetryEvent) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TelemetryEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TelemetryEvent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *TelemetryEvent) GetEventCategory() string {
	if x != nil {
		return x.EventCategory
	}
	return ""
}

func (x *TelemetryEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *TelemetryEvent) GetTid() uint32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *TelemetryEvent) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *TelemetryEvent) GetProcessExe() string {
	if x != nil {
		return x.ProcessExe
	}
	return ""
}

func (x *TelemetryEvent) GetProcessCmdline() string {
	if x != nil {
		return x.ProcessCmdline
	}
	return ""
}

func (x *TelemetryEvent) GetParentPid() uint32 {
	if x != nil {
		return x.ParentPid
	}
	return 0
}

func (x *TelemetryEvent) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

func (x *TelemetryEvent) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *TelemetryEvent) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TelemetryEvent) GetRawEvent() []byte {
	if x != nil {
		return x.RawEvent
	}
	return nil
}

type TelemetryBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Events        []*TelemetryEvent      `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *TelemetryBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TelemetryBatch) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *TelemetryBatch) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *TelemetryBatch) GetEvents() []*TelemetryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type TelemetryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int64                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryAck) Reset() {
	*x = TelemetryAck{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryAck) ProtoMessage() {}

func (x *TelemetryAck) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryAck.ProtoReflect.Descriptor instead.
func (*TelemetryAck) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{6}
}

func (x *TelemetryAck) GetAccepted() int64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

type DetectionReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	AgentHostname string                 `protobuf:"bytes,3,opt,name=agent_hostname,json=agentHostname,proto3" json:"agent_hostname,omitempty"`
	RuleId        string                 `protobuf:"bytes,4,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleName      string                 `protobuf:"bytes,5,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Severity      string                 `protobuf:"bytes,9,opt,name=severity,proto3" json:"severity,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	// Events that triggered the detection, as JSON bytes.
	Events        []byte                 `protobuf:"bytes,12,opt,name=events,proto3" json:"events,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionReport) Reset() {
	*x = DetectionReport{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionReport) ProtoMessage() {}

func (x *DetectionReport) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionReport.ProtoReflect.Descriptor instead.
func (*DetectionReport) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{7}
}

func (x *DetectionReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DetectionReport) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *DetectionReport) GetAgentHostname() string {
	if x != nil {
		return x.AgentHostname
	}
	return ""
}

func (x *DetectionReport) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *DetectionReport) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *DetectionReport) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DetectionReport) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DetectionReport) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DetectionReport) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *DetectionReport) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DetectionReport) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DetectionReport) GetEvents() []byte {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *DetectionReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type DetectionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DetectionId   string                 `protobuf:"bytes,1,opt,name=detection_id,json=detectionId,proto3" json:"detection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionAck) Reset() {
	*x = DetectionAck{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionAck) ProtoMessage() {}

func (x *DetectionAck) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionAck.ProtoReflect.Descriptor instead.
func (*DetectionAck) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{8}
}

func (x *DetectionAck) GetDetectionId() string {
	if x != nil {
		return x.DetectionId
	}
	return ""
}

type RuleSubscription struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	OrgId   string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Current rules version hash. Server sends update only if different.
	CurrentVersion string `protobuf:"bytes,3,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuleSubscription) Reset() {
	*x = RuleSubscription{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSubscription) ProtoMessage() {}

func (x *RuleSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSubscription.ProtoReflect.Descriptor instead.
func (*RuleSubscription) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{9}
}

func (x *RuleSubscription) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RuleSubscription) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *RuleSubscription) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

type RuleUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full ruleset YAML (one document per rule, separated by ---).
	RulesYaml []byte `protobuf:"bytes,1,opt,name=rules_yaml,json=rulesYaml,proto3" json:"rules_yaml,omitempty"`
	// Macros YAML (combined macros document).
	MacrosYaml []byte `protobuf:"bytes,2,opt,name=macros_yaml,json=macrosYaml,proto3" json:"macros_yaml,omitempty"`
	// Version hash of this ruleset.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Number of rules included.
	RuleCount     int32 `protobuf:"varint,4,opt,name=rule_count,json=ruleCount,proto3" json:"rule_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleUpdate) Reset() {
	*x = RuleUpdate{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleUpdate) ProtoMessage() {}

func (x *RuleUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleUpdate.ProtoReflect.Descriptor instead.
func (*RuleUpdate) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{10}
}

func (x *RuleUpdate) GetRulesYaml() []byte {
	if x != nil {
		return x.RulesYaml
	}
	return nil
}

func (x *RuleUpdate) GetMacrosYaml() []byte {
	if x != nil {
		return x.MacrosYaml
	}
	return nil
}

func (x *RuleUpdate) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RuleUpdate) GetRuleCount() int32 {
	if x != nil {
		return x.RuleCount
	}
	return 0
}

type CommandPush struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Command payload as JSON bytes (varies by command type).
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandPush) Reset() {
	*x = CommandPush{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandPush) ProtoMessage() {}

func (x *CommandPush) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandPush.ProtoReflect.Descriptor instead.
func (*CommandPush) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{11}
}

func (x *CommandPush) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandPush) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CommandPush) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CommandResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First message on the stream identifies the agent.
	// Subsequent messages carry command results.
	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CommandId     string `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "completed" or "failed"
	Result        []byte `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{12}
}

func (x *CommandResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandResult) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CommandResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	EngineVersion string                 `protobuf:"bytes,4,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	// PEM-encoded certificate signing request.
	Csr           string `protobuf:"bytes,5,opt,name=csr,proto3" json:"csr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{13}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *EnrollRequest) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *EnrollRequest) GetCsr() string {
	if x != nil {
		return x.Csr
	}
	return ""
}

type EnrollResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	OrgId   string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// PEM-encoded signed agent certificate.
	SignedCert string `protobuf:"bytes,3,opt,name=signed_cert,json=signedCert,proto3" json:"signed_cert,omitempty"`
	// PEM-encoded CA certificate for verifying the server.
	CaCert        string `protobuf:"bytes,4,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{14}
}

func (x *EnrollResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrollResponse) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *EnrollResponse) GetSignedCert() string {
	if x != nil {
		return x.SignedCert
	}
	return ""
}

func (x *EnrollResponse) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

var File_fleet_v1_fleet_proto protoreflect.FileDescriptor

const file_fleet_v1_fleet_proto_rawDesc = "" +
	"\n" +
	"\x14fleet/v1/fleet.proto\x12\bfleet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x02\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"os_version\x18\x02 \x01(\tR\tosVersion\x12%\n" +
	"\x0eengine_version\x18\x03 \x01(\tR\rengineVersion\x12\x1f\n" +
	"\vagent_group\x18\x04 \x01(\tR\n" +
	"agentGroup\x127\n" +
	"\x04tags\x18\x05 \x03(\v2#.fleet.v1.RegisterRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x85\x02\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\rrules_version\x18\x03 \x01(\tR\frulesVersion\x12\x17\n" +
	"\acpu_pct\x18\x04 \x01(\x01R\x06cpuPct\x12\x15\n" +
	"\x06mem_mb\x18\x05 \x01(\x04R\x05memMb\x12$\n" +
	"\x0eevents_per_sec\x18\x06 \x01(\x01R\feventsPerSec\x12!\n" +
	"\factive_rules\x18\a \x01(\x05R\vactiveRules\"\xa5\x01\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12+\n" +
	"\x11tamper_protection\x18\x02 \x01(\bR\x10tamperProtection\x12\x1a\n" +
	"\bisolated\x18\x03 \x01(\bR\bisolated\x12/\n" +
	"\x13isolation_whitelist\x18\x04 \x03(\tR\x12isolationWhitelist\"\xc4\x03\n" +
	"\x0eTelemetryEvent\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_name\x18\x03 \x01(\tR\teventName\x12%\n" +
	"\x0eevent_category\x18\x04 \x01(\tR\reventCategory\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\rR\x03pid\x12\x10\n" +
	"\x03tid\x18\x06 \x01(\rR\x03tid\x12!\n" +
	"\fprocess_name\x18\a \x01(\tR\vprocessName\x12\x1f\n" +
	"\vprocess_exe\x18\b \x01(\tR\n" +
	"processExe\x12'\n" +
	"\x0fprocess_cmdline\x18\t \x01(\tR\x0eprocessCmdline\x12\x1d\n" +
	"\n" +
	"parent_pid\x18\n" +
	" \x01(\rR\tparentPid\x12\x1f\n" +
	"\vparent_name\x18\v \x01(\tR\n" +
	"parentName\x12\x16\n" +
	"\x06params\x18\f \x01(\fR\x06params\x12\x1a\n" +
	"\bmetadata\x18\r \x01(\fR\bmetadata\x12\x1b\n" +
	"\traw_event\x18\x0e \x01(\fR\brawEvent\"\x90\x01\n" +
	"\x0eTelemetryBatch\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x120\n" +
	"\x06events\x18\x04 \x03(\v2\x18.fleet.v1.TelemetryEventR\x06events\"*\n" +
	"\fTelemetryAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x03R\baccepted\"\xe8\x03\n" +
	"\x0fDetectionReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12%\n" +
	"\x0eagent_hostname\x18\x03 \x01(\tR\ragentHostname\x12\x17\n" +
	"\arule_id\x18\x04 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\trule_name\x18\x05 \x01(\tR\bruleName\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\a \x01(\tR\x04text\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1a\n" +
	"\bseverity\x18\t \x01(\tR\bseverity\x12=\n" +
	"\x06labels\x18\n" +
	" \x03(\v2%.fleet.v1.DetectionReport.LabelsEntryR\x06labels\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x12\x16\n" +
	"\x06events\x18\f \x01(\fR\x06events\x128\n" +
	"\ttimestamp\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\fDetectionAck\x12!\n" +
	"\fdetection_id\x18\x01 \x01(\tR\vdetectionId\"m\n" +
	"\x10RuleSubscription\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12'\n" +
	"\x0fcurrent_version\x18\x03 \x01(\tR\x0ecurrentVersion\"\x85\x01\n" +
	"\n" +
	"RuleUpdate\x12\x1d\n" +
	"\n" +
	"rules_yaml\x18\x01 \x01(\fR\trulesYaml\x12\x1f\n" +
	"\vmacros_yaml\x18\x02 \x01(\fR\n" +
	"macrosYaml\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"rule_count\x18\x04 \x01(\x05R\truleCount\"K\n" +
	"\vCommandPush\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x9e\x01\n" +
	"\rCommandResult\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x04 \x01(\fR\x06result\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\x99\x01\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12%\n" +
	"\x0eengine_version\x18\x04 \x01(\tR\rengineVersion\x12\x10\n" +
	"\x03csr\x18\x05 \x01(\tR\x03csr\"|\n" +
	"\x0eEnrollResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x1f\n" +
	"\vsigned_cert\x18\x03 \x01(\tR\n" +
	"signedCert\x12\x17\n" +
	"\aca_cert\x18\x04 \x01(\tR\x06caCert2\xae\x03\n" +
	"\fAgentService\x12A\n" +
	"\bRegister\x12\x19.fleet.v1.RegisterRequest\x1a\x1a.fleet.v1.RegisterResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.fleet.v1.HeartbeatRequest\x1a\x1b.fleet.v1.HeartbeatResponse\x12E\n" +
	"\x0fStreamTelemetry\x12\x18.fleet.v1.TelemetryBatch\x1a\x16.fleet.v1.TelemetryAck(\x01\x12B\n" +
	"\rSendDetection\x12\x19.fleet.v1.DetectionReport\x1a\x16.fleet.v1.DetectionAck\x12D\n" +
	"\x0eSubscribeRules\x12\x1a.fleet.v1.RuleSubscription\x1a\x14.fleet.v1.RuleUpdate0\x01\x12D\n" +
	"\x0eCommandChannel\x12\x17.fleet.v1.CommandResult\x1a\x15.fleet.v1.CommandPush(\x010\x012P\n" +
	"\x11EnrollmentService\x12;\n" +
	"\x06Enroll\x12\x17.fleet.v1.EnrollRequest\x1a\x18.fleet.v1.EnrollResponseB.Z,github.com/rabbitstack/fibratus/pkg/fleet/pbb\x06proto3"

var (
	file_fleet_v1_fleet_proto_rawDescOnce sync.Once
	file_fleet_v1_fleet_proto_rawDescData []byte
)

func file_fleet_v1_fleet_proto_rawDescGZIP() []byte {
	file_fleet_v1_fleet_proto_rawDescOnce.Do(func() {
		file_fleet_v1_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_v1_fleet_proto_rawDesc), len(file_fleet_v1_fleet_proto_rawDesc)))
	})
	return file_fleet_v1_fleet_proto_rawDescData
}

var file_fleet_v1_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_fleet_v1_fleet_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: fleet.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 1: fleet.v1.RegisterResponse
	(*HeartbeatRequest)(nil),      // 2: fleet.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 3: fleet.v1.HeartbeatResponse
	(*TelemetryEvent)(nil),        // 4: fleet.v1.TelemetryEvent
	(*TelemetryBatch)(nil),        // 5: fleet.v1.TelemetryBatch
	(*TelemetryAck)(nil),          // 6: fleet.v1.TelemetryAck
	(*DetectionReport)(nil),       // 7: fleet.v1.DetectionReport
	(*DetectionAck)(nil),          // 8: fleet.v1.DetectionAck
	(*RuleSubscription)(nil),      // 9: fleet.v1.RuleSubscription
	(*RuleUpdate)(nil),            // 10: fleet.v1.RuleUpdate
	(*CommandPush)(nil),           // 11: fleet.v1.CommandPush
	(*CommandResult)(nil),         // 12: fleet.v1.CommandResult
	(*EnrollRequest)(nil),         // 13: fleet.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 14: fleet.v1.EnrollResponse
	nil,                           // 15: fleet.v1.RegisterRequest.TagsEntry
	nil,                           // 16: fleet.v1.DetectionReport.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_fleet_v1_fleet_proto_depIdxs = []int32{
	15, // 0: fleet.v1.RegisterRequest.tags:type_name -> fleet.v1.RegisterRequest.TagsEntry
	17, // 1: fleet.v1.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	17, // 2: fleet.v1.TelemetryEvent.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 3: fleet.v1.TelemetryBatch.events:type_name -> fleet.v1.TelemetryEvent
	16, // 4: fleet.v1.DetectionReport.labels:type_name -> fleet.v1.DetectionReport.LabelsEntry
	17, // 5: fleet.v1.DetectionReport.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 6: fleet.v1.AgentService.Register:input_type -> fleet.v1.RegisterRequest
	2,  // 7: fleet.v1.AgentService.Heartbeat:input_type -> fleet.v1.HeartbeatRequest
	5,  // 8: fleet.v1.AgentService.StreamTelemetry:input_type -> fleet.v1.TelemetryBatch
	7,  // 9: fleet.v1.AgentService.SendDetection:input_type -> fleet.v1.DetectionReport
	9,  // 10: fleet.v1.AgentService.SubscribeRules:input_type -> fleet.v1.RuleSubscription
	12, // 11: fleet.v1.AgentService.CommandChannel:input_type -> fleet.v1.CommandResult
	13, // 12: fleet.v1.EnrollmentService.Enroll:input_type -> fleet.v1.EnrollRequest
	1,  // 13: fleet.v1.AgentService.Register:output_type -> fleet.v1.RegisterResponse
	3,  // 14: fleet.v1.AgentService.Heartbeat:output_type -> fleet.v1.HeartbeatResponse
	6,  // 15: fleet.v1.AgentService.StreamTelemetry:output_type -> fleet.v1.TelemetryAck
	8,  // 16: fleet.v1.AgentService.SendDetection:output_type -> fleet.v1.DetectionAck
	10, // 17: fleet.v1.AgentService.SubscribeRules:output_type -> fleet.v1.RuleUpdate
	11, // 18: fleet.v1.AgentService.CommandChannel:output_type -> fleet.v1.CommandPush
	14, // 19: fleet.v1.EnrollmentService.Enroll:output_type -> fleet.v1.EnrollResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_fleet_v1_fleet_proto_init() }
func file_fleet_v1_fleet_proto_init() {
	if File_fleet_v1_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_v1_fleet_proto_rawDesc), len(file_fleet_v1_fleet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_fleet_v1_fleet_proto_goTypes,
		DependencyIndexes: file_fleet_v1_fleet_proto_depIdxs,
		MessageInfos:      file_fleet_v1_fleet_proto_msgTypes,
	}.Build()
	File_fleet_v1_fleet_proto = out.File
	file_fleet_v1_fleet_proto_goTypes = nil
	file_fleet_v1_fleet_proto_depIdxs = nil
}
